---
version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 22
        commands:
            - npm i
    pre_build:
        commands:
            - echo 'Running linter'
            - npm run lint
    build:
        commands:
            - echo 'Building'
            - npm run generate
artifacts:
    files:
        - ./**/*
    base-directory: '.output/public'
